### ISSUE TITLE
Allow developing composite actions within its own repository

### ISSUE THREAD

**Issue by SimonSchwendele** [YunaBraska/github-workflow-plugin#15]
## Description
I'm currently developing a lot of composite actions which should be used across a variety of repositories.
This plugin however is currently only activated whenever the yml file resides in `.github/workflows/*.yml`

## Background
You can push a composite action into its own repository and reference it like this

```yml
      - name: Do stuff with composite action
        uses: Owner/repo@branch
        with:
           input1: 'thing'
           input2: 'otherThing'
```

which means Im pushing repositories like this:

```bash
$ ls -a
.  ..  action.yml  .git   .gitignore  .idea
$ tree
.
└── action.yml

1 directory, 1 file
```

## Request
This Plugin should recognize the existence of a compsite action
