### ISSUE TITLE
Workflow stored in private repository no longer works

### ISSUE THREAD

**Issue by erichiller** [YunaBraska/github-workflow-plugin#29]
**What happened?**
Recently, within the last three days, this plug-in reports incorrect parameters for included workflows. Previously it did not report any errors. Nothing has changed in either the parent or included workflows.
I have my private repo authenticated in Rider, no changes there.

I'm not sure whether the Rider 2023.2.2 release or the 3.0.0 release of this extension broke this functionality as they came out the same day.

**Relevant log output**
_Unsure how to get logs_

**Operating System**
Ubuntu

**Plugin Version**
3.0.0

**IDE Name and Version**
Rider 2023.2.2

Example of parent file include (see the position of the _# ERROR SQUIGGLES ON THE BELOW_ comment):
```yml
  test:
    uses: user/repo/.github/workflows/sub-dotnet-test-simple.yaml@master
    permissions:
      contents: read
      packages: read
    with:
      # ERROR SQUIGGLES ON THE BELOW
      TEST_PROJECT: 'MyProj.Tests'
```

example of `user/repo/.github/workflows/sub-dotnet-test-simple.yaml@master`:

```yml
name: .NET Simple Test

on:
  workflow_call:
    inputs:
      TEST_PROJECT:
        required: true
        type: string
```
