### ISSUE TITLE
Variables/Outputs used in `fromJson` are marked as unused

### ISSUE THREAD

**Issue by Lordfirespeed** [YunaBraska/github-workflow-plugin#46]
**What happened?**

**How can we reproduce the issue?**
```yaml
name: Reproduce Issue

on:
  workflow_dispatch: 

jobs:
  list-folders:
    runs-on: ubuntu-latest
    outputs: 
      folders: ${{ steps.list.outputs.folders }}
    steps:
      - name: List folders
        id: list
        uses: kmanimaran/list-folder-action@v4
        with:
          path: ./Games
          
  update-all:
    runs-on: ubuntu-latest
    needs: list-folders
    strategy: 
      matrix:
        folder: ${{ fromJson(needs.list-folders.outputs.games) }}
```

The `folders` output of the `list-folders` task is greyed out with reason: 'unused'. 

**Relevant log output**
> N/A

**Operating System**
> Pop!_OS 22.04 

**Plugin Version**
> v3.2.1

**IDE Name and Version**
> Rider 2023.2.3

**Expected behavior**
The `folders` output of the `list-folders` task should not be greyed out.

**Screenshots**

**Additional context**
