### ISSUE TITLE
sub-actions are not well supported

### ISSUE THREAD

**Issue by LecrisUT** [YunaBraska/github-workflow-plugin#48]
Truncated workflow example:
```yaml
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python, javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
```

The issue is sporadic and temporary, but sometimes, the first variant `github/codeql-action/init` is detected, while `github/codeql-action/analyze` needs to be first interacted with before it is fully navigable. Moreover it should report as `github/codeql-action/init`, but instead it is reported as simply `github/codeql-action`
