### ISSUE TITLE
needs.<job_id>.result not currently supported

### ISSUE THREAD

**Issue by enobrev** [YunaBraska/github-workflow-plugin#54]
**Is your feature request related to a problem? Please describe.**
When trying to reference the result of a `needs` object, I get a red squiggle with an error of "Incomplete statement [`needs.<job_id>.result`]"

**Describe the solution you'd like**
Add support for [`needs.<job_id>.result`](https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context)

**Describe alternatives you've considered**
I'm not sure there's any alternatives.  I've been ignoring the red squiggle for the time being.

**Operating System**
Ubuntu 22.04.4 LTS

**Project Version**
3.2.1

**Additional context**
Here is a test workflow to demonstrate the issue:

```yml
name: Bug Report

on:
  workflow_dispatch:

jobs:
  some_job:
    name: Previous Job
    runs-on: ubuntu-latest

    outputs:
      test: ${{ steps.vars.outputs.test }}

    steps:
      - name: Test Vars
        id: vars
        run: echo "test=1" >> $GITHUB_OUTPUT

  next_job:
    needs: [some_job]
    name: Reference Job
    runs-on: ubuntu-latest

    steps:
      - name: Slack Message Vars
        id: vars
        run: |
          echo "Result: ${{ needs.some_job.result }}"
          echo "Value: ${{ needs.some_job.outputs.test }}"
```

And I'm attaching a screenshot to show the squiggle.  As you can see, the `outputs` works correctly.  It's just the `result` that's missing.

![Screenshot from 2024-03-11 15-32-43](https://github.com/YunaBraska/github-workflow-plugin/assets/584126/563a8d7d-35bf-423d-a582-69903983f8ce)
