### ISSUE TITLE
@JetBrains/qodana-action is unrecognized

### ISSUE THREAD

**Issue by InSyncWithFoo** [YunaBraska/github-workflow-plugin#55]
The plugin says `JetBrains/qodana-action@v2023.3.1` cannot be resolved.

![](https://github.com/YunaBraska/github-workflow-plugin/assets/122007197/80f9fbac-b79e-4119-92db-99bb33feb1a6)

Yet the `v2023.3.1` tag [exists](https://github.com/JetBrains/qodana-action/releases/tag/v2023.3.1).

### Minimal reproducible example

```yaml
on:
  workflow_dispatch:

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: JetBrains/qodana-action@v2023.3.1
```

### Environment

* OS: Windows 10
* Plugin version: 3.2.1
* IDE: IntelliJ IDEA 2023.3.5 (CE)
