### ISSUE TITLE
Invalid error inspection on composite action?

### ISSUE THREAD

**Issue by jbw9964** [YunaBraska/github-workflow-plugin#76]
Hello. I was practicing workflows and think I've found something weired.

I've made a composite action like below.

```yaml
name: Build application

description: 'Setup JDK 17 & build application via gradle.'

inputs:
  working_dir:
    required: true
    default: './'
    description: 'A directory where gradlew exists'

  java_version:
    required: true
    default: 17
    description: 'JDK version'

  distribution:
    required: true
    default: 'temurin'
    description: 'JDK distribution'

runs:
  using: composite

  steps:
    - name: Check whether gradlew exists
      shell: bash
      run: |
        if [ ! -f ${{ inputs.working_dir }}gradlew ]; then
          echo "No gradlew exists on working directory ${{ inputs.working_dir }}"
          exit 1
        fi

    - name: Change gradlew permission
      shell: bash
      run: chmod +x ${{ inputs.working_dir }}gradlew

    - name: Cache gradle
      uses: actions/cache@v4
      id: cache-gradle    # <-- step id to reference
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java_version }}
        distribution: ${{ inputs.distribution }}

    - name: Build if no gradle cache found
      if: steps.cache-gradle.outputs.cache-hit != 'true'         # <-- Shows `Delete invalid [cache-gradle]`
      shell: bash
      run: |
        echo "No gradle found via cache. Running gradlew build..."
        ${{ inputs.working_dir }}gradlew build -x test
```

When I run above action, no error occurs in GitHub action.

However, in my IDE, it shows an error inspection like below.

<img width="818" alt="Image" src="https://github.com/user-attachments/assets/5707df8e-c14f-44b5-8595-3140d4b5e4a0" />

Is it a bug or did I make a silly mistake on somewhere?

Since I'm little on workflow, I want to know more details.
Will you help me?

**Operating System**
> macOS Sequoia 15.3, M1

**Project Version**
> IntelliJ IDEA 2024.3.3 (Ultimate Edition)
> Github-Workflow plugin : 2024.3.0
